export const WOMENS_PRODUCT_REQUEST = "WOMENS_PRODUCT_REQUEST"
export const WOMENS_PRODUCT_FAILURE = "WOMENS_PRODUCT_FAILURE"



// GET PRODUCT
export const GET_WOMENS_PRODUCT_SUCCESS = "GET_WOMENS_PRODUCT_SUCCESS"