export const MENS_PRODUCT_REQUEST = "MENS_PRODUCT_REQUEST"
export const MENS_PRODUCT_FAILURE = "MENS_PRODUCT_FAILURE"



// GET PRODUCT
export const GET_MENS_PRODUCT_SUCCESS = "GET_MENS_PRODUCT_SUCCESS"

// POST PRODUCT
export const ADD_TO_CART_MENS_PRODUCT_SUCCESS = "ADD_TO_CART_MENS_PRODUCT_SUCCESS"
