export const MENS_REQUEST = "MENS_REQUEST"
export const MENS_FAILURE = "MENS_FAILURE"



// GET PRODUCT
export const GET_MENS_SUCCESS = "GET_MENS_SUCCESS"

// POST PRODUCT
export const ADD_MENS_SUCCESS = "ADD_MENS_SUCCESS"

// UPDATE MENS QUANTITY
export const UPDATE_MENS_QUANTITY = "UPDATE_MENS_QUANTITY"
