export const CART_REQUEST = "CART_REQUEST"
export const CART_FAILURE = "MENS_PRODUCT_FAILURE"



// GET PRODUCT
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"

// POST PRODUCT
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"

// UPDATE CART QUANTITY
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY"
