export const KIDS_PRODUCT_REQUEST = "KIDS_PRODUCT_REQUEST"
export const KIDS_PRODUCT_FAILURE = "KIDS_PRODUCT_FAILURE"



// GET PRODUCT
export const GET_KIDS_PRODUCT_SUCCESS = "GET_KIDS_PRODUCT_SUCCESS"

// POST PRODUCT
export const ADD_TO_CART_KIDS_PRODUCT_SUCCESS = "ADD_TO_CART_KIDS_PRODUCT_SUCCESS"
